os: linux,
language: node_js
node_js:
  stable
dist: trusty
cache: npm
jobs:
  include:
    stage: deploy,
    name: Deploy to production
    script: npm run build
    
deploy: 
  provider: heroku
  api_key: 
    secure: $HK_KEY
  on: master
  github_token: GH_TOKEN
