os: linux
language: node_js
node_js:
- 10
dist: trusty
deploy:
  provider: heroku
  api_key:
    secure: GhqEkUuOoTRHZIvikLhSgPjARE86X0jzo6BVNUGlM54xAPdKO2C/lLHjw/jBLDs8z4Y8csEPDTB8Gmt209iURIgt0Yaxh/yvdEULWhx4T7JM8dZHWgzAX06Nny7Gltxdhpa2/kVWgIr2M5AfWOhdxZkxbTyc+LKQcEMeOhnlm/RxOfWKCHAAdr+TwfHmWQLdGJXERuIQrOlB18n+Y9icxaJpVZNG7Qirf530RgKF9KbDvtdbCFQbO8ZupQudS+79pbARZ8xTzpvKAWO6mNL6XbS9yx7JW/jOKp4OFk1ksW7YU8OaHG8kSdOb/hZe6VHEy38XRRdwURmJT6pJpDwbdQCywCnKGEWTdpJJKl/mQFMrL0ZO7Su4sX0V/43AxM2bik3l0OKwlCiEAz032/UW2cjOt7GKCMZA7uGpHA2kXalSn1nCvllYEpdLw+mrZKuGGFSVTrlSMG8gWcdg9yWk42XoZEHGEZTyQYULeLKXjTdPFfGvnzibWuXfrBYufK5bcR9QbsmrEFLEbARpiOmfI+qzLF5pbCy2mF/i8U7lWrfLNNWkKCup0D3wThCnD91rLYYRK9qCgdzYaaCQEtio/gt9WUTxjbBzyQSOVvdocox+EfQRLrGHx6e570CSroBPYhVQ6LKLV2sNPFC6X9tZn5LWj1D67I85p8APGzKKHXs=
  app: wizard-app-challenge
  skip_cleanup: true
jobs:
  include:
  - stage: tests
    name: Unit tests
    script: npm run test:unit
  - stage: deploy
    name: Deploy to production
    script: npm run build
